# Generated by Django 4.2.3 on 2023-07-16 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_jp', models.CharField(blank=True, max_length=100, null=True)),
                ('genre_en', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Japanese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_a', models.CharField(blank=True, max_length=100, null=True)),
                ('topic_b', models.CharField(blank=True, max_length=100, null=True)),
                ('genre_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='word_wolf.genre')),
            ],
        ),
        migrations.CreateModel(
            name='English',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_a', models.CharField(blank=True, max_length=100, null=True)),
                ('topic_b', models.CharField(blank=True, max_length=100, null=True)),
                ('genre_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='word_wolf.genre')),
            ],
        ),
    ]
