# Generated by Django 4.2.3 on 2023-08-16 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word_wolf', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='genre_jp',
        ),
        migrations.DeleteModel(
            name='Japanese',
        ),
    ]
